name: CI/CD Pipeline

# Trigger configurations (choose as needed)
on:
  # Standard push/pull request triggers
  push:
    branches: [ "main", "dev" ]
    paths:
      - '**.java'
      - 'pom.xml'
      - '.github/workflows/**'
      - 'src/**'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
              distribution: 'temurin'
              java-version: '21'
              cache: 'maven'
        - name: build
          run: mvn clean package
        
