name: springboot

on: 
  - push

jobs:
  Building-docker:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v4
          - name: Setup Maven Action
            uses: s4u/setup-maven-action@v2
          - run: mvn -V ...
        
  
